### ISSUE TITLE
Create a Makefile for BasicRT

### ISSUE THREAD

**Issue by edwardparkers** [edwardparkers/BasicRT#1]
Create a Makefile for compiling the whole project. It should included with the proper warning & optimization flags.
Also the C++17 standard must be followed.

**Comment by Hridoy-31** [comment]
Hello @edwardparkers, can I work on this issue ? Currently I am learning C++. So, I think, I can help. Thanks in advance.

**Comment by edwardparkers** [comment]
Sure. Go on. Welcome

**Comment by edwardparkers** [comment]
Closed with PR #2
