### ISSUE TITLE
Ray-Sphere Implementation

### ISSUE THREAD

**Issue by edwardparkers** [edwardparkers/BasicRT#3]
Implement the ray-sphere intersection for the `basicrt` ray-tracer in the `Class sphere`. Don't forget to test it. Compile with the `Makefile` and run it. Try to produce every corner case work perfectly for the code you will write.

**Comment by Hridoy-31** [comment]
Hi @edwardparkers, I am very much likely to work with this.

**Comment by edwardparkers** [comment]
Yes, @Hridoy-31. You can go ahead. Looking forward for your contribution !

**Comment by edwardparkers** [comment]
Closed by PR #4
