### ISSUE TITLE
render scene implementation

### ISSUE THREAD

**Issue by edwardparkers** [edwardparkers/BasicRT#5]
In the `main` function, create a scene that is composed of 1 light and 5 spheres. Light is also considered as a sphere. After implementing the scene, render the full scene. And this process should be done by calling `render()` function in `main` function

**Comment by Hridoy-31** [comment]
Because of the implementation of the `main` function in the previous PR, I like to take it. If you want to give it to another person, feel free to do that. Thanks !

**Comment by edwardparkers** [comment]
Sure, @Hridoy-31. Go on, man. Your contributions are very much crisp. Thanks in advance. You have good testing skills by the way !

**Comment by Hridoy-31** [comment]
It's my pleasure !!

**Comment by edwardparkers** [comment]
Closed with PR #6
