### ISSUE TITLE
recursion depth implementation

### ISSUE THREAD

**Issue by edwardparkers** [edwardparkers/BasicRT#7]
Create a function named `mix` which will return `float`. In this function, implement the maximum recursion depth that `basicrt` can handle.

**Comment by Hridoy-31** [comment]
Hello @edwardparkers. I like to work on this issue. I have a plan to set the recursion depth minimum as 5. If this resonates with you what you want, then I can continue to contribute.

**Comment by edwardparkers** [comment]
Sure, it works fine for me. Go ahead, @Hridoy-31

**Comment by edwardparkers** [comment]
Closed with PR #8
