### ISSUE TITLE
Trace Function Implementation

### ISSUE THREAD

**Issue by edwardparkers** [edwardparkers/BasicRT#9]
Implement the main trace function. The function will take ray as argument. Check also the ray intersect any of the geometry or not. If intersect, then compute the intersection point. and it's normal. Also shade this point for better viewing. But remember, Shading depends on the surface property of the geometry. The function will return a color of ray. If Intersect. then return the color of the object in which the ray is intersected or return the color of the background.

**Comment by Hridoy-31** [comment]
Hello @edwardparkers, can I work on this issue ? Please let me know. Thanks

**Comment by edwardparkers** [comment]
Yes, of course. Without a doubt. Go on

**Comment by edwardparkers** [comment]
Closed with PR #10
